"""
Pydantic models for SiteAuditor
"""
from .schemas import (
    AnalyzeRequest,
    AnalyzeResponse,
    SEOResult,
    SecurityResult,
    TechStackResult,
    BrokenLinksResult,
    CoreWebVitals,
    LighthouseScores,
    SecurityHeader,
    SSLInfo,
    Technology,
    BrokenLink,
    AuditStatus,
    SeverityLevel,
    ExposedFile,
    CompanyInfo,
    ContactInfo,
    GDPRResult,
    CookieItem,
    SMOResult,
    GreenResult,
    DNSHealthResult
)

__all__ = [
    "AnalyzeRequest",
    "AnalyzeResponse",
    "SEOResult",
    "SecurityResult",
    "TechStackResult",
    "BrokenLinksResult",
    "CoreWebVitals",
    "LighthouseScores",
    "SecurityHeader",
    "SSLInfo",
    "Technology",
    "BrokenLink",
    "AuditStatus",
    "SeverityLevel",
    "ExposedFile",
    "CompanyInfo",
    "ContactInfo",
    "GDPRResult",
    "CookieItem",
    "SMOResult",
    "GreenResult",
    "DNSHealthResult"
]
